export const styles = {
  backdrop: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: "8px",
    width: "90%",
    maxWidth: "80%",
    boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
    overflow: "hidden",
  },
  modeCashback: {
    color: "green",
    fontWeight: 500,
  },
  modeInvest: {
    color: "#1e40af",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem",
    borderBottom: "1px solid #e5e7eb",
    backgroundColor: "#f9fafb",
  },
  closeButton: {
    backgroundColor: "#fff",
    border: "2px solid red",
    borderRadius: "50%",
    width: "28px",
    height: "28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1rem",
    fontWeight: "bold",
    color: "red",
    cursor: "pointer",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "1.55rem",
    backgroundColor: "#fff",
    border: "1px solid #d1d5db",
  },
  thead: {
    backgroundColor: "#f3f4f6",
    textAlign: "left" as const,
  },
  th: {
    padding: "0.75rem",
    fontWeight: 600,
    color: "#374151",
    fontSize: "0.85rem",
    border: "1px solid #62748eff",
  },
  tbody: {
    backgroundColor: "#fff",
  },
  tr: {
    borderBottom: "1px solid #e5e7eb",
  },
  td: {
    padding: "0.75rem",
    color: "#4b5563",
    fontSize: "1rem",
    border: "1px solid #62748eff",
  },
  cardno: {
    padding: "0.75rem",
    color: "#ee1b54ff",
    fontSize: "1rem",
    fontWeight: "bold",
    border: "1px solid #62748eff",
  },
  pagination: {
    padding: "1rem",
    display: "flex",
    justifyContent: "space-between",
    borderTop: "1px solid #e5e7eb",
    backgroundColor: "#f9fafb",
  },
  loaderOverlay: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255,255,255,0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  loader: {
    width: "32px",
    height: "32px",
    border: "4px solid #ccc",
    borderTopColor: "#10b981",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
};