export const styles: { [key: string]: React.CSSProperties } = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  card: {
    backgroundColor: "#fff",
    padding: "24px",
    borderRadius: "8px",
    width: "900px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem",
    borderBottom: "1px solid #e5e7eb",
    backgroundColor: "#f9fafb",
  },
  closeButton: {
    backgroundColor: "#fff",
    border: "2px solid red",
    borderRadius: "50%",
    width: "25px",
    height: "25px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1rem",
    fontWeight: "bold",
    color: "red",
    cursor: "pointer",
    padding: 0,
    lineHeight: 1,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "0.95rem",
    backgroundColor: "#fff",
    overflowX: "auto" as const,
    border: "1px solid #7b7d82ff",
  },
  thead: {
    backgroundColor: "#f3f4f6",
    textAlign: "left" as const,
    borderBottom: "2px solid #e5e7eb",
    padding: "10%",
  },
  th: {
    padding: "1rem",
    fontWeight: 700,
    color: "#374151",
    fontSize: "1rem",
  },
  tbody: {
    backgroundColor: "#fff",
  },
  tr: {
    borderBottom: "1px solid #e5e7eb",
    transition: "background-color 0.2s ease-in-out",
  },
  td: {
    padding: "0.75rem",
    color: "#4b5563",
    fontSize: "0.95rem",
  },
  trHover: {
    backgroundColor: "#f9fafb",
  },
  pagination: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "12px",
  },
  pageInfo: {
    fontWeight: "bold",
    color: "#555",
  },
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    marginTop: "16px",
  },
};