// styles.ts
export const styles = {
  backdrop: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: "8px",
    width: "70%",
    boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
    overflow: "hidden",
    animation: "fadeIn 0.3s ease-in-out",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem",
    borderBottom: "1px solid #e5e7eb",
    backgroundColor: "#f9fafb",
  },
  closeButton: {
    backgroundColor: "#fff",
    border: "2px solid red",
    borderRadius: "50%",
    width: "25px",
    height: "25px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1rem",
    fontWeight: "bold",
    color: "red",
    cursor: "pointer",
    padding: 0,
    lineHeight: 1,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "0.95rem",
    backgroundColor: "#fff",
    overflowX: "auto" as const,
    border: "1px solid #7b7d82ff",
  },
  thead: {
    backgroundColor: "#f3f4f6",
    textAlign: "left" as const,
    borderBottom: "2px solid #e5e7eb",
  },
  th: {
    padding: "0.75rem",
    fontWeight: 600,
    color: "#374151",
    fontSize: "0.85rem",
  },
  tbody: {
    backgroundColor: "#fff",
  },
  tr: {
    borderBottom: "1px solid #e5e7eb",
    transition: "background-color 0.2s ease-in-out",
  },
  td: {
    padding: "0.75rem",
    color: "#4b5563",
    fontSize: "0.95rem",
  },
  trHover: {
    backgroundColor: "#f9fafb",
  },

  pagination: {
    padding: "1rem",
    display: "flex",
    justifyContent: "space-between",
    borderTop: "1px solid #e5e7eb",
    backgroundColor: "#f9fafb",
  },
};